apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true" # Enable Regex
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Prefix /rabbitmq;
spec:
  ingressClassName: nginx
  rules:
    - host: {{ alb_dns_name }}
      http:
        paths:
          - path: /rabbitmq(/|$)(.*)  # Capture everything after /rabbitmq
            pathType: ImplementationSpecific
            backend:
              service:
                name: rabbitmq-service
                port:
                  number: 15672