name: Deploy Auto Scaler

on:
  workflow_run:
    workflows: ["K3s deployment using Ansible"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy-asg-and-workers:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv infra/venv
          
          # Call pip directly from the venv folder
          infra/venv/bin/pip install --upgrade pip
          infra/venv/bin/pip install -r infra/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi Sync and Deploy - Autoscaler
        env:
          PULUMI_PYTHON_CMD: ../../venv/bin/python
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          GIT_RUNNER_IP=$(pulumi stack output git_runner_public_ip --cwd infra/k3s-cluster/master -s dev)
          MASTER_NODE_IP=$(pulumi stack output master_private_ip --cwd infra/k3s-cluster/master -s dev)
          
          # Save the kubeconfig into a variable
          # Hop through Git-runner to reach the Master Private IP
          KUBEDATA=$(ssh -o StrictHostKeyChecking=no -A ubuntu@$GIT_RUNNER_IP \
            "ssh -o StrictHostKeyChecking=no ubuntu@$MASTER_NODE_IP 'sudo cat /etc/rancher/k3s/k3s.yaml'")
          
          # Clean the config (replace 127.0.0.1 with the Master Private IP)
          export KUBECONFIG_CONTENT=$(echo "$KUBEDATA" | sed "s/127.0.0.1/$MASTER_NODE_IP/g")
          
          pulumi stack select dev --create --cwd infra/k3s-cluster/worker
          pulumi refresh --yes --cwd infra/k3s-cluster/worker
          pulumi up --yes --cwd infra/k3s-cluster/worker
