name: Deploy Smart Scaler to Lambda
on:
  workflow_run:
    workflows: ["Apply Kubernetes Manifests"]
    types:
      - completed

  workflow_dispatch:

jobs:
  deploy-smart-scaler:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          # Go to the folder where requirements.txt lives
          cd functions/smart-scaler
    
          pip install -r requirements.txt -t ./src

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Zip Bundle
        run: |
          cd functions/smart-scaler/src
          zip -r ../../../deploy.zip .

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi Refresh - Autoscaler
        run: |
          pulumi stack select dev --cwd infra/k3s-cluster/worker
          pulumi refresh --yes --cwd infra/k3s-cluster/worker

      - name: Save Pulumi outputs
        id: pulumi_outputs
        run: |
          LAMBDA_FUNCTION_NAME=$(pulumi stack output lambda_function_name --cwd infra/k3s-cluster/worker -s dev)
          
          echo "LAMBDA_FUNCTION_NAME=$LAMBDA_FUNCTION_NAME" >> $GITHUB_ENV
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Update Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://deploy.zip