name: Deploy Infrastructure

on:
  push:
    branches:
      - master
    paths:
      - infra/common/**
      - infra/k3s-cluster/master/**

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv infra/venv
          
          # Call pip directly from the venv folder
          infra/venv/bin/pip install --upgrade pip
          infra/venv/bin/pip install -r infra/requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Set public key as github env
        run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Pulumi Sync and Deploy - Common
        env:
          PULUMI_PYTHON_CMD: ../venv/bin/python
        run: |
          pulumi stack select dev --create --cwd infra/common
          pulumi refresh --yes --cwd infra/common
          pulumi up --yes --cwd infra/common

      - name: Pulumi Sync and Deploy - Master
        env:
          PULUMI_PYTHON_CMD: ../../venv/bin/python
        run: |
          pulumi stack select dev --create --cwd infra/k3s-cluster/master
          pulumi refresh --yes --cwd infra/k3s-cluster/master
          pulumi up --yes --cwd infra/k3s-cluster/master

